CE: 1
SRMv2: 3
GridFtp: 5
LFC: 6
FTS: 7
Submit Node: 109
# ^ This is used for both Schedds and Glidein Frontends.
OSG_Display: 116
Software Cache: 119
OSG Homepage: 120
OSG DOCDB: 121
Glidein factory: 122
Software Repo: 123
Apache Server: 129
net.perfSONAR.Bandwidth: 130
net.perfSONAR.Latency: 131
CVMFS Stratum-1: 132
Oasis Server: 133
Software Repo Mirror: 135
Squid: 138
Condor Collector: 139
oasis-login: 140
XRootD component: 142
Cassandra DB: 144
perfsonar data store: 145
Connect: 149
XRootD origin server: 147
XRootD cache server: 156
XRootD HA component: 148
Virtual Machine Host: 150
Certificate Provider: 151
Message Bus: 154
Topology Server: 155
Execution Endpoint: 157
WebDAV: 158
WebDAV.disk: 161
WebDAV.tape: 162
SRMv2.disk: 159
SRMv2.tape: 160
# deprecated
GUMS Server: 101
VOMS Server: 102
Gratia Collector: 103
RSV Collector: 104
# unsupported
SRMv1: 2
OSG BDII: 105
Twiki Server: 106
ReSS Collector: 108
VOMRS Server: 110
WLCG Interoperability BDII: 111
MyOSG: 112
VOMS_Monitoring: 113
CADIST_Monitoring: 114
CRL_Monitoring: 115
GOCTicket: 117
OIM: 118
OSG-JIRA: 126
(removed): 134
Ticket Exchange: 136
GratiaWeb: 141
OSG blogs: 143

