name: Validate Topology code
on: [push, pull_request]

jobs:
  validate-code:
    name: Validate Topology code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.15
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install apache2-dev libldap2-dev libsasl2-dev libyaml-dev
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-apache.txt
          python -m pip install pytest pytest-mock
      - name: Test API
        run: |
          export TOPOLOGY_CONFIG=$PWD/src/config-ci.py
          export FLASK_DEBUG=1
          py.test ./src/tests/test_api.py
      - name: Test StashCache
        run: |
          export TOPOLOGY_CONFIG=$PWD/src/config-ci.py
          export FLASK_DEBUG=1
          py.test ./src/tests/test_stashcache.py
      - name: Test cacher
        run: |
          ./src/topology_cacher.py --outdir=/tmp/topology-cacher
